apiVersion: v1
kind: Secret
metadata:
  name: mongodb-user-credentials
  namespace: mongodb
type: Opaque
stringData:
  dbUser-password: MongoDBPass123!
  dbAdmin-password: MongoDBPass123!
  sysAdmin-password: MongoDBPass123!
