apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mongodb-demo-mdb

resources:
  - namespace.yaml
  - ../../base

patches:
  # Patch MongoDB deployment
  - target:
      kind: MongoDB
      name: mongodb-deployment
    patch: |-
      - op: replace
        path: /metadata/name
        value: demo-mdb
      - op: replace
        path: /spec/type
        value: Standalone
      - op: replace
        path: /spec/members
        value: 1
      - op: replace
        path: /spec/opsManager/configMapRef/name
        value: ops-manager-connection
      - op: replace
        path: /spec/podSpec/podTemplate/spec/containers/0/resources/limits/cpu
        value: "2"
      - op: replace
        path: /spec/podSpec/podTemplate/spec/containers/0/resources/limits/memory
        value: 4Gi

  # Patch Ops Manager ConfigMap
  - target:
      kind: ConfigMap
      name: ops-manager-connection
    patch: |-
      - op: replace
        path: /data/orgId
        value: "69a34148d21fd11d35c6554c"
      - op: replace
        path: /data/projectName
        value: "demo-mdb"

  # Patch Service
  - target:
      kind: Service
      name: mongodb-external
    patch: |-
      - op: replace
        path: /metadata/name
        value: demo-mdb-external
      - op: replace
        path: /spec/selector/app
        value: demo-mdb-svc
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30101

  # Patch MongoDBUser resources
  - target:
      kind: MongoDBUser
      name: dbuser
    patch: |-
      - op: replace
        path: /metadata/name
        value: dbuser
      - op: replace
        path: /spec/mongodbResourceRef/name
        value: demo-mdb

  - target:
      kind: MongoDBUser
      name: dbadmin
    patch: |-
      - op: replace
        path: /metadata/name
        value: dbadmin
      - op: replace
        path: /spec/mongodbResourceRef/name
        value: demo-mdb

  - target:
      kind: MongoDBUser
      name: sysadmin
    patch: |-
      - op: replace
        path: /metadata/name
        value: sysadmin
      - op: replace
        path: /spec/mongodbResourceRef/name
        value: demo-mdb
